import { UserType } from '../../../utils/types';

export type QuizType = {
  _id?: string; // populate
  id: string;
  uuid: string;
  title: string;
  isDeleted: boolean;
  questionsAndAnswers: {
    question: string;
    answer: string;
    options: string[];
    isTheory: boolean;
  }[];
  isCriticalThinkingQuiz: boolean;
};

export type QuizAttemptType = {
  id: string;
  score: number;
  quizId: string;
  quiz?: QuizType | null;
  userId: string;
  user?: UserType | null;
  createdAt: Date; // auto-generated by MongoDB
  updatedAt: Date; // auto-generated by MongoDB
  answers: {
    question: string;
    answer: string;
  }[];

  hasPassed: boolean; // Virtual field to indicate if the attempt has passed based on score and passing criteria
};

export enum QuizDisplayCriteriaEnum {
  END = 'end',
  MIDPOINT = 'midpoint',
}
