import { ProgrammeType } from "./programme.type";
import { QuizAttemptType, QuizType } from "./quiz.type";

export type ContentType = {
  id: string;
  uuid: string;
  priority: number;
  title: string;
  description: string;
  format: string;
  content: string;
  badgeCriteria: string;
  quizDisplayCriteria: string;
  category: string;
  isFeatured: boolean;
  isDeleted: boolean;
  programmeId: string | null;
  programme?: ProgrammeType | null;
  badgeId: string | null;
  badge?: {};
  quizId: string | null;
  quiz?: QuizType | null;
  criticalThinkingQuizId: string | null;
  criticalThinkingQuiz?: QuizType | null;
  thumbnail: string;
  season: number;
  cast: string[];
  views: number;
  quizAttempt?: QuizAttemptType | null;
  isPreviousCompleted?: boolean; // Virtual field to indicate if previous content's quiz is completed

  createdAt?: Date; // auto-generated by MongoDB
  updatedAt?: Date; // auto-generated by MongoDB

  pdfUrl?: string | null; // Optional field for PDF content

  storyStopId: string | null;
  pledgeId: string | null;
};

export enum ContentBadgeCriteriaEnum {
  END = "end",
  MIDPOINT = "midpoint",
  START = "start",
  QUIZ = "quiz",
}

export enum ContentQuizDisplayCriteriaEnum {
  END = "end",
  MIDPOINT = "midpoint",
  START = "start",
}

export type ViewingHistoryStatType = {
  name: string;
  watched: number;
  totalContent: number;
};

export enum ContentFormatEnum {
  VIDEO = "video",
  AUDIO = "audio",
}
