export type QuizType = {
  _id?: string; // populate
  id: string;
  uuid: string;
  title: string;
  questionsAndAnswers: QnAType[];
};

export type QuizAttemptType = {
  id: string;
  score: number;
  quizId: string;
  quiz?: QuizType | null;
  userId: string;
  user?: QuizType | null;
  createdAt: Date; // auto-generated by MongoDB
  updatedAt: Date; // auto-generated by MongoDB

  hasPassed: boolean; // Virtual field to indicate if the attempt has passed based on score and passing criteria
};

export type QnAType = {
  question: string;
  answer: string;
  options: string[];
  minAge: number;
  maxAge: number;
};
